### ISSUE TITLE
What kind of CAD software used for PCB? no gerber files!

### ISSUE THREAD

**Issue by sbhamad** [helios-4/wiki#15]
Hi Kobol,

I cannot find a way to open the files in this link https://wiki.kobol.io/files/carrier/Helios4_PCB_R1-1.zip

I cannot find the gerber files or do not know how to get them for the Helios4. Any ideas?

I thought this was open source.

Cheers,
SAEED

**Comment by aprayoga** [comment]
Hi SAEED,

To open the file you need to use Mentor PCB Layout Browser. We already put the link just below the PCB file link on our wiki.

Here is the link to download the software
https://www.mentor.com/pcb/downloads/browsers/

Regards,
Aditya

**Comment by g-provost** [comment]
@sbhamad Gerber and Assembly files of Helios4 PCB carrier has just been added to the wiki.

**Comment by sbhamad** [comment]
HELIOS-4 - rev1.1-AssyPS pdf file is inverted, kindly fix and re-upload.

![image](https://user-images.githubusercontent.com/18968640/53810599-5e22d300-3f68-11e9-9dd0-2c37acc68511.png)
