### ISSUE TITLE
Menu not working on mobile

### ISSUE THREAD

**Issue by yalp** [helios-4/wiki#18]
The wiki menu button does not seem to work anymore on Safari/iOS12. Same goes for the search button. 
The menu and search buttons are temporarily grayed after tap but navigation menu / search do not appear.

**Comment by g-provost** [comment]
@yalp Thanks for reporting the issue, now it's fixed.

I recently updated to latest mkdocs-material version and I didn't realize some templates tweak weren't aligned with latest version and therefore not working in responsive mode. Looks like I didn't check properly the impact of the update :/
