### ISSUE TITLE
Wake-on-LAN is kinda mixed up

### ISSUE THREAD

**Issue by anothernewusername** [helios-4/wiki#21]
The section about enabling WOL (https://wiki.kobol.io/wol/#enabling-wol) seems to mix different states of development.

In the first note it says:

> Latest Armbian images, starting version 5.77, should already have the WoL enabled by default for eth0. Check that file /lib/systemd/system/**helios4-wol.service** exist and match the configuration file below.

The mentioned "file below" is called:

> To make it permanent, create the following file /lib/systemd/system/**wol@.service** and copy the following

Furthermore the content of said file in the wiki is:

> `[Unit]
> Description=Wake-on-LAN for %i
> After=network-online.target
> Wants=network-online.target
> 
> [Service]
> ExecStart=/sbin/ethtool -s %i wol g
> Type=oneshot
> 
> [Install]
> WantedBy=multi-user.target`

While it looks like the following on my system running Armbian 5.91:

> `[Unit]
> Description=Enable Wake-on-LAN for Helios4 eth0
> Requires=network.target
> After=network.target
> 
> [Service]
> ExecStart=/sbin/ethtool -s eth0 wol g
> Type=oneshot
> 
> [Install]
> WantedBy=multi-user.target
> `

Maybe you want to clean things up for new users. Thanks in advance :)

**Comment by g-provost** [comment]
You right, it was a bit confusing. Fixed.
