### ISSUE TITLE
Dupont Cables

### ISSUE THREAD

**Issue by zwack-am** [helios-4/wiki#5]
In docs/i2c.md 

You need to use female to female cables not male to male.  The pins stick out on both the Helios4 and the OLED module that I purchased.  They are Male.  If your cable had sticking out pins on both ends it would be Male to Male.

I have to say that for the price (about $6) this was an insanely easy and useful mod.

**Comment by g-provost** [comment]
Fixed. Thanks for pinpointing, it was a silly mistake.

**Comment by zwack-am** [comment]
No problem, if it had been a bigger change I would have submitted a PR but I figured this was minor enough that it wasn't worth me cloning your repo, fixing it and then submitting a PR.

I am looking at the NOR flash at the moment and my machine is not seeing any mtd devices, even with the workaround enabled.  If nothing springs to mind don't worry I will spend some more time looking into it before I ask for assistance.

Thanks,
Adam

On October 6, 2018 9:57:19 AM PDT, Gauthier Provost <notifications@github.com> wrote:
>Fixed. Thanks for pinpointing, it was a silly mistake.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/helios-4/wiki/issues/5#issuecomment-427589445

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by zwack-am** [comment]
Maybe, at least I now know the issue.   

Thanks.

On October 6, 2018 10:27:20 AM PDT, Gauthier Provost <notifications@github.com> wrote:
>Please ignore all instruction related to SPI NOR + Armbian. We are
>still preparing a PR for Armbian in order to add the Helios4 SPI
>support. Maybe we shouldn't have publish the wiki page in advance.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/helios-4/wiki/issues/5#issuecomment-427591888

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
